Feature/mirror new modifier
StarAppeal/express-uwu-rest pull request #14
Opened 2022-05-18 16:26 UTC by tsomic

2022-05-19 17:58 UTC, StarAppeal commented on src/constants/maps/mirror.ts
> +  ä: "ɒ̈",
Keine Möglichkeit für Ö, Ü?

2022-05-19 18:54 UTC, StarAppeal requested changes
Ein Träumchen, schau dir aber noch ö und ü an.

2022-05-19 18:58 UTC, tsomic commented on src/constants/maps/mirror.ts
> +  ä: "ɒ̈",
Hm, hab ich einfach weggelassen weil die gespiegelt gleich sind. Sollte es aber konsistent machen, hast recht

2022-05-20 22:15 UTC, StarAppeal approved these changes
LGTM!

2022-05-20 22:15 UTC, merged